const items = [
  { code: "962", name: "240v Variac", item_type: "240v_variac" },
  { code: "633", name: "3 Way Refrigerator", item_type: "3_way_refrigerator" },
  { code: "1122", name: "3D Printer", item_type: "3d_printer" },
  { code: "681", name: "3Ph Angle Meter", item_type: "3ph_angle_meter" },
  { code: "686", name: "3Ph Band Saw", item_type: "3ph_band_saw" },
  { code: "1295", name: "3Ph Battery Charger", item_type: "3ph_battery_charger" },
  { code: "1365", name: "3Ph Canning Machine", item_type: "3ph_canning_machine" },
  { code: "658", name: "3Ph Compressor", item_type: "3ph_compressor" },
  { code: "690", name: "3Ph Cut Off Machine", item_type: "3ph_cut_off_machine" },
  { code: "1355", name: "3Ph Dishwasher", item_type: "3ph_dishwasher" },
  { code: "701", name: "3Ph Distribution Box", item_type: "3ph_distribution_box" },
  { code: "1344", name: "3Ph DMX Controller", item_type: "3ph_dmx_controller" },
  { code: "583", name: "3Ph Dough Maker", item_type: "3ph_dough_maker" },
  { code: "580", name: "3Ph Dough Press", item_type: "3ph_dough_press" },
  { code: "1345", name: "3Ph Dowling Jig", item_type: "3ph_dowling_jig" },
  { code: "693", name: "3Ph Dust Extractor", item_type: "3ph_dust_extractor" },
  { code: "732", name: "3Ph Dyna Fan", item_type: "3ph_dyna_fan" },
  { code: "695", name: "3Ph Extension Lead", item_type: "3ph_extension_lead" },
  { code: "694", name: "3Ph Fertilizer Spreader", item_type: "3ph_fertilizer_spreader" },
  { code: "710", name: "3Ph Food Press", item_type: "3ph_food_press" },
  { code: "687", name: "3Ph Furnace", item_type: "3ph_furnace" },
  { code: "1081", name: "3Ph Glass Washer", item_type: "3ph_glass_washer" },
  { code: "656", name: "3Ph Grinder", item_type: "3ph_grinder" },
  { code: "653", name: "3Ph Hack Saw", item_type: "3ph_hack_saw" },
  { code: "1074", name: "3Ph Homogenizer", item_type: "3ph_homogenizer" },
  { code: "702", name: "3Ph Hydraulic Panel", item_type: "3ph_hydraulic_panel" },
  { code: "654", name: "3Ph Lathe", item_type: "3ph_lathe" },
  { code: "659", name: "3Ph Lead", item_type: "3ph_lead" },
  { code: "1138", name: "3Ph Leather Splitter", item_type: "3ph_leather_splitter" },
  { code: "787", name: "3Ph Maxi Grow", item_type: "3ph_maxi_grow" },
  { code: "704", name: "3Ph Milling Machine", item_type: "3ph_milling_machine" },
  { code: "712", name: "3Ph Mincer/Mixer", item_type: "3ph_mincer_mixer" },
  { code: "655", name: "3Ph Motor", item_type: "3ph_motor" },
  { code: "1352", name: "3Ph Multi Vac", item_type: "3ph_multi_vac" },
  { code: "709", name: "3Ph Nibbler", item_type: "3ph_nibbler" },
  { code: "707", name: "3Ph Oven", item_type: "3ph_oven" },
  { code: "699", name: "3Ph Part Cleaner", item_type: "3ph_part_cleaner" },
  { code: "1298", name: "3Ph Paternoster", item_type: "3ph_paternoster" },
  { code: "733", name: "3Ph Pipe Bender", item_type: "3ph_pipe_bender" },
  { code: "1346", name: "3Ph Planer", item_type: "3ph_planer" },
  { code: "700", name: "3Ph Plasma Cutter", item_type: "3ph_plasma_cutter" },
  { code: "1292", name: "3Ph Press", item_type: "3ph_press" },
  { code: "657", name: "3Ph Pump", item_type: "3ph_pump" },
  { code: "788", name: "3Ph RCD Box", item_type: "3ph_rcd_box" },
  { code: "708", name: "3Ph Refrigerator", item_type: "3ph_refrigerator" },
  { code: "1350", name: "3Ph Router", item_type: "3ph_router" },
  { code: "682", name: "3Ph Salimander", item_type: "3ph_salimander" },
  { code: "1082", name: "3Ph Sanitizer", item_type: "3ph_sanitizer" },
  { code: "705", name: "3Ph Saw", item_type: "3ph_saw" },
  { code: "696", name: "3Ph Shaker", item_type: "3ph_shaker" },
  { code: "1347", name: "3Ph Sheer", item_type: "3ph_sheer" },
  { code: "706", name: "3Ph Sheeter", item_type: "3ph_sheeter" },
  { code: "703", name: "3Ph Shifter", item_type: "3ph_shifter" },
  { code: "697", name: "3Ph Shot Blaster", item_type: "3ph_shot_blaster" },
  { code: "685", name: "3Ph Spindle", item_type: "3ph_spindle" },
  { code: "692", name: "3Ph Terminal Block", item_type: "3ph_terminal_block" },
  { code: "684", name: "3Ph Test Panel", item_type: "3ph_test_panel" },
  { code: "688", name: "3Ph Thermol", item_type: "3ph_thermol" },
  { code: "1348", name: "3Ph Thicknesser", item_type: "3ph_thicknesser" },
  { code: "683", name: "3Ph Transformer", item_type: "3ph_transformer" },
  { code: "1293", name: "3Ph Vacuum Press", item_type: "3ph_vacuum_press" },
  { code: "534", name: "3Ph Vari Speed Drive", item_type: "3ph_vari_speed_drive" },
  { code: "651", name: "3Ph Variac", item_type: "3ph_variac" },
  { code: "1137", name: "3Ph Washing Machine", item_type: "3ph_washing_machine" },
  { code: "652", name: "3Ph Welder", item_type: "3ph_welder" },
  { code: "691", name: "3Ph Wheel Balancer", item_type: "3ph_wheel_balancer" },
  { code: "799", name: "3Ph Work Station", item_type: "3ph_work_station" },
  { code: "443", name: "AC Adaptor-sealed", item_type: "ac_adaptor_sealed" },
  { code: "122", name: "Aerator", item_type: "aerator" },
  { code: "123", name: "Aerial", item_type: "aerial" },
  { code: "542", name: "Aerial Booster", item_type: "aerial_booster" },
  { code: "125", name: "Aero-Neb", item_type: "aero_neb" },
  { code: "1218", name: "Aggregometer", item_type: "aggregometer" },
  { code: "127", name: "Agitator", item_type: "agitator" },
  { code: "781", name: "Air Bag Press", item_type: "air_bag_press" },
  { code: "452", name: "Air Compressor", item_type: "air_compressor" },
  { code: "563", name: "Air Con (Portable)", item_type: "air_con_portable" },
  { code: "422", name: "Air Conditioner", item_type: "air_conditioner" },
  { code: "1349", name: "Air Dryer", item_type: "air_dryer" },
  { code: "811", name: "Air Filter/Purifier", item_type: "air_filter_purifier" },
  { code: "129", name: "Air Hockey", item_type: "air_hockey" },
  { code: "937", name: "Air Mattress", item_type: "air_mattress" },
  { code: "989", name: "Air Monitor /Sampler", item_type: "air_monitor_sampler" },
  { code: "130", name: "Air Pump", item_type: "air_pump" },
  { code: "548", name: "Air Velocity Tx", item_type: "air_velocity_tx" },
  { code: "729", name: "Airless Painter", item_type: "airless_painter" },
  { code: "132", name: "Alarm Bell/Panel", item_type: "alarm_bell_panel" },
  { code: "1214", name: "Allergy Tester", item_type: "allergy_tester" },
  { code: "734", name: "Alternator Test Bench", item_type: "alternator_test_bench" },
  { code: "1280", name: "Amalgamator", item_type: "amalgamator" },
  { code: "891", name: "Ammeter", item_type: "ammeter" },
  { code: "1042", name: "Analyser", item_type: "analyser" },
  { code: "481", name: "Angle Grinder", item_type: "angle_grinder" },
  { code: "135", name: "Answering Machine", item_type: "answering_machine" },
  { code: "566", name: "Appliance Tester", item_type: "appliance_tester" },
  { code: "137", name: "Aquarium Filter/Pump", item_type: "aquarium_filter_pump" },
  { code: "143", name: "Aquarium Heater", item_type: "aquarium_heater" },
  { code: "138", name: "Aquarium light", item_type: "aquarium_light" },
  { code: "812", name: "Aquarium Pump", item_type: "aquarium_pump" },
  { code: "639", name: "Arm Guard System", item_type: "arm_guard_system" },
  { code: "549", name: "Armture Growler", item_type: "armture_growler" },
  { code: "145", name: "Atlas light", item_type: "atlas_light" },
  { code: "147", name: "Audio Equipment", item_type: "audio_equipment" },
  { code: "1226", name: "Audiometer", item_type: "audiometer" },
  { code: "148", name: "Austar", item_type: "austar" },
  { code: "1004", name: "Auto Packager", item_type: "auto_packager" },
  { code: "846", name: "Autoclave", item_type: "autoclave" },
  { code: "1362", name: "Autograph S-500", item_type: "autograph_s_500" },
  { code: "1180", name: "Autosampler", item_type: "autosampler" },
  { code: "815", name: "AV - Other", item_type: "av_other" },
  { code: "454", name: "AV Amplifier", item_type: "av_amplifier" },
  { code: "814", name: "AV Lights (Various)", item_type: "av_lights_various" },
  { code: "238", name: "Bag/Vacuum Sealer", item_type: "bag_vacuum_sealer" },
  { code: "550", name: "Balancing Rig", item_type: "balancing_rig" },
  { code: "579", name: "Barbecue", item_type: "barbecue" },
  { code: "241", name: "Barcode Reader", item_type: "barcode_reader" },
  { code: "1175", name: "Bare Hugger", item_type: "bare_hugger" },
  { code: "782", name: "Barrel Washer", item_type: "barrel_washer" },
  { code: "464", name: "Battery Charger", item_type: "battery_charger" },
  { code: "873", name: "Battery Charger WSHOP", item_type: "battery_charger_wshop" },
  { code: "242", name: "Bay Maree", item_type: "bay_maree" },
  { code: "957", name: "Bearing Heater", item_type: "bearing_heater" },
  { code: "330", name: "Belt Sander", item_type: "belt_sander" },
  { code: "300", name: "Binder", item_type: "binder" },
  { code: "331", name: "Biscuit Cutter/Jointer", item_type: "biscuit_cutter_jointer" },
  { code: "735", name: "Blanket Warmer", item_type: "blanket_warmer" },
  { code: "736", name: "Blood Fridge", item_type: "blood_fridge" },
  { code: "1170", name: "Blood Pressure Test", item_type: "blood_pressure_test" },
  { code: "1217", name: "Blood Tester", item_type: "blood_tester" },
  { code: "831", name: "Blower/Vacuum", item_type: "blower_vacuum" },
  { code: "1330", name: "Bone Station", item_type: "bone_station" },
  { code: "559", name: "Book Coverer", item_type: "book_coverer" },
  { code: "942", name: "Bottle Warmer", item_type: "bottle_warmer" },
  { code: "244", name: "Braille Machine", item_type: "braille_machine" },
  { code: "720", name: "Brake Lathe", item_type: "brake_lathe" },
  { code: "896", name: "Breakout Box", item_type: "breakout_box" },
  { code: "838", name: "Brick Saw", item_type: "brick_saw" },
  { code: "626", name: "Bty Air Treatment", item_type: "bty_air_treatment" },
  { code: "612", name: "Bty Barrel Waver", item_type: "bty_barrel_waver" },
  { code: "628", name: "Bty Brush & Peel", item_type: "bty_brush_peel" },
  { code: "795", name: "Bty Chair", item_type: "bty_chair" },
  { code: "629", name: "Bty Curling Lamp", item_type: "bty_curling_lamp" },
  { code: "613", name: "Bty Electrolysis Equip", item_type: "bty_electrolysis_equip" },
  { code: "796", name: "Bty Face Steamer", item_type: "bty_face_steamer" },
  { code: "609", name: "Bty Foot Massager", item_type: "bty_foot_massager" },
  { code: "605", name: "Bty Hair Clippers", item_type: "bty_hair_clippers" },
  { code: "600", name: "Bty Hair Crimper", item_type: "bty_hair_crimper" },
  { code: "602", name: "Bty Hair Curler/Brush", item_type: "bty_hair_curler_brush" },
  { code: "631", name: "Bty Hair Dryer Pedastal", item_type: "bty_hair_dryer_pedastal" },
  { code: "601", name: "Bty Hair Ext. Equip", item_type: "bty_hair_ext_equip" },
  { code: "604", name: "Bty Hair Microscope", item_type: "bty_hair_microscope" },
  { code: "603", name: "Bty Hair Steamer", item_type: "bty_hair_steamer" },
  { code: "636", name: "Bty Heat Lamp/Fan", item_type: "bty_heat_lamp_fan" },
  { code: "598", name: "Bty Hot Rollers", item_type: "bty_hot_rollers" },
  { code: "597", name: "Bty Hot Sticks", item_type: "bty_hot_sticks" },
  { code: "797", name: "Bty Magic Mirror", item_type: "bty_magic_mirror" },
  { code: "610", name: "Bty Massager", item_type: "bty_massager" },
  { code: "611", name: "Bty Mirror", item_type: "bty_mirror" },
  { code: "606", name: "Bty Nail Drill", item_type: "bty_nail_drill" },
  { code: "607", name: "Bty Nail Fan", item_type: "bty_nail_fan" },
  { code: "616", name: "Bty Perm Machine", item_type: "bty_perm_machine" },
  { code: "630", name: "Bty Permanent Wave", item_type: "bty_permanent_wave" },
  { code: "554", name: "Bty Razor", item_type: "bty_razor" },
  { code: "634", name: "Bty Roller", item_type: "bty_roller" },
  { code: "632", name: "Bty Rotary Brush", item_type: "bty_rotary_brush" },
  { code: "614", name: "Bty Steriliser", item_type: "bty_steriliser" },
  { code: "798", name: "Bty Towel Warmer", item_type: "bty_towel_warmer" },
  { code: "627", name: "Bty UV Skin Analyser", item_type: "bty_uv_skin_analyser" },
  { code: "643", name: "Bty Vac Body Equip", item_type: "bty_vac_body_equip" },
  { code: "608", name: "Bty Wax Pot", item_type: "bty_wax_pot" },
  { code: "817", name: "Bubble Machine", item_type: "bubble_machine" },
  { code: "246", name: "Bubble Spa", item_type: "bubble_spa" },
  { code: "551", name: "Bubbler", item_type: "bubbler" },
  { code: "247", name: "Bug Zapper", item_type: "bug_zapper" },
  { code: "465", name: "Calculator 240V", item_type: "calculator_240v" },
  { code: "1072", name: "Calibrator", item_type: "calibrator" },
  { code: "961", name: "Calorimeter", item_type: "calorimeter" },
  { code: "1108", name: "Calorimeter", item_type: "calorimeter" },
  { code: "762", name: "Camera Adaptor", item_type: "camera_adaptor" },
  { code: "993", name: "Cancer Treatment Unit", item_type: "cancer_treatment_unit" },
  { code: "990", name: "Cannulated Cleaner", item_type: "cannulated_cleaner" },
  { code: "537", name: "Card Reader /Cashier", item_type: "card_reader_cashier" },
  { code: "1357", name: "Cardioscope", item_type: "cardioscope" },
  { code: "800", name: "Carpet Steamer", item_type: "carpet_steamer" },
  { code: "440", name: "Cash Register", item_type: "cash_register" },
  { code: "813", name: "CB / any comms", item_type: "cb_any_comms" },
  { code: "531", name: "CD/DVD/Hard Drive", item_type: "cd_dvd_hard_drive" },
  { code: "159", name: "CD/Tape/Radio/Stereo", item_type: "cd_tape_radio_stereo" },
  { code: "255", name: "Cement Mixer", item_type: "cement_mixer" },
  { code: "160", name: "Centrifuge bench", item_type: "centrifuge_bench" },
  { code: "324", name: "Chain Saw electric", item_type: "chain_saw_electric" },
  { code: "737", name: "Chair Electric", item_type: "chair_electric" },
  { code: "256", name: "Chair Lift", item_type: "chair_lift" },
  { code: "399", name: "Change table", item_type: "change_table" },
  { code: "259", name: "Channel Control", item_type: "channel_control" },
  { code: "730", name: "Chassis Dyno", item_type: "chassis_dyno" },
  { code: "1283", name: "Chest Drain Trainer", item_type: "chest_drain_trainer" },
  { code: "943", name: "Chlorinator", item_type: "chlorinator" },
  { code: "1322", name: "Chocolate Fountain", item_type: "chocolate_fountain" },
  { code: "1161", name: "Chromatograph", item_type: "chromatograph" },
  { code: "985", name: "Citoborma", item_type: "citoborma" },
  { code: "956", name: "Clay Extruder", item_type: "clay_extruder" },
  { code: "260", name: "Clock", item_type: "clock" },
  { code: "818", name: "Clock Bundy", item_type: "clock_bundy" },
  { code: "261", name: "Clock Radio", item_type: "clock_radio" },
  { code: "262", name: "Clockmatic", item_type: "clockmatic" },
  { code: "282", name: "Clothes Dryer/Cabinet", item_type: "clothes_dryer_cabinet" },
  { code: "455", name: "Clothes Iron", item_type: "clothes_iron" },
  { code: "193", name: "Clothes Iron Press", item_type: "clothes_iron_press" },
  { code: "263", name: "Coin Dispenser/Counter", item_type: "coin_dispenser_counter" },
  { code: "1371", name: "Colibri", item_type: "colibri" },
  { code: "301", name: "Collator", item_type: "collator" },
  { code: "161", name: "Colorimeter", item_type: "colorimeter" },
  { code: "958", name: "Colour Comparator", item_type: "colour_comparator" },
  { code: "163", name: "Colour Wheel", item_type: "colour_wheel" },
  { code: "801", name: "Combo Oscilloscope", item_type: "combo_oscilloscope" },
  { code: "433", name: "Comms Cabinet/Hub", item_type: "comms_cabinet_hub" },
  { code: "426", name: "Computer (CPU)", item_type: "computer_cpu" },
  { code: "887", name: "Condenser Tester", item_type: "condenser_tester" },
  { code: "763", name: "Conductivity Tester", item_type: "conductivity_tester" },
  { code: "1024", name: "Controller", item_type: "controller" },
  { code: "264", name: "Convertor", item_type: "convertor" },
  { code: "890", name: "Conveyor Belt", item_type: "conveyor_belt" },
  { code: "885", name: "Conveyor Interface Mod", item_type: "conveyor_interface_mod" },
  { code: "1186", name: "Cooling Module", item_type: "cooling_module" },
  { code: "265", name: "Copy aid", item_type: "copy_aid" },
  { code: "165", name: "Counter Timer", item_type: "counter_timer" },
  { code: "266", name: "Cover System", item_type: "cover_system" },
  { code: "1207", name: "Coverslipper", item_type: "coverslipper" },
  { code: "1145", name: "Crack Detector", item_type: "crack_detector" },
  { code: "254", name: "CRT Display", item_type: "crt_display" },
  { code: "783", name: "Crusher", item_type: "crusher" },
  { code: "1209", name: "Cryostat", item_type: "cryostat" },
  { code: "1147", name: "Cupping Tester", item_type: "cupping_tester" },
  { code: "1047", name: "Cure System", item_type: "cure_system" },
  { code: "1234", name: "Curing light", item_type: "curing_light" },
  { code: "267", name: "Curling Brush", item_type: "curling_brush" },
  { code: "1162", name: "Curve Tracer", item_type: "curve_tracer" },
  { code: "268", name: "Cushions", item_type: "cushions" },
  { code: "269", name: "Cyber Shot", item_type: "cyber_shot" },
  { code: "1264", name: "Cycler", item_type: "cycler" },
  { code: "1325", name: "Decloaking Chamber", item_type: "decloaking_chamber" },
  { code: "270", name: "Decoration", item_type: "decoration" },
  { code: "1369", name: "Degaser", item_type: "degaser" },
  { code: "951", name: "Degaussing", item_type: "degaussing" },
  { code: "819", name: "Dehumidifier", item_type: "dehumidifier" },
  { code: "195", name: "Dehydrator", item_type: "dehydrator" },
  { code: "271", name: "Del Humder", item_type: "del_humder" },
  { code: "197", name: "Demagnetiser", item_type: "demagnetiser" },
  { code: "1181", name: "Denaturant Gene System", item_type: "denaturant_gene_system" },
  { code: "1083", name: "Densitometer", item_type: "densitometer" },
  { code: "1242", name: "Dental Bench", item_type: "dental_bench" },
  { code: "1033", name: "Dental Grinder", item_type: "dental_grinder" },
  { code: "1249", name: "Dental Vibrator", item_type: "dental_vibrator" },
  { code: "1250", name: "Denture Cleaner", item_type: "denture_cleaner" },
  { code: "272", name: "Desensitiser", item_type: "desensitiser" },
  { code: "273", name: "Detector", item_type: "detector" },
  { code: "276", name: "Developer", item_type: "developer" },
  { code: "713", name: "Diagnostic Machine", item_type: "diagnostic_machine" },
  { code: "278", name: "Digi Box", item_type: "digi_box" },
  { code: "1095", name: "Digi Staltic", item_type: "digi_staltic" },
  { code: "1105", name: "Digital Designer", item_type: "digital_designer" },
  { code: "945", name: "Digital Photo Frame", item_type: "digital_photo_frame" },
  { code: "1167", name: "Digital Programmer", item_type: "digital_programmer" },
  { code: "866", name: "Digital Set Top Box", item_type: "digital_set_top_box" },
  { code: "1281", name: "Directview CR System", item_type: "directview_cr_system" },
  { code: "738", name: "Disinfector", item_type: "disinfector" },
  { code: "1359", name: "Disintegrator", item_type: "disintegrator" },
  { code: "1196", name: "Dispenser", item_type: "dispenser" },
  { code: "1021", name: "Disposal Station", item_type: "disposal_station" },
  { code: "1092", name: "Distortion Meter", item_type: "distortion_meter" },
  { code: "1136", name: "Distributor Check", item_type: "distributor_check" },
  { code: "540", name: "Door Chime", item_type: "door_chime" },
  { code: "1077", name: "Dose-It", item_type: "dose_it" },
  { code: "1160", name: "Dosimat", item_type: "dosimat" },
  { code: "555", name: "Drafting Plotter", item_type: "drafting_plotter" },
  { code: "1044", name: "Drain Cleaner", item_type: "drain_cleaner" },
  { code: "430", name: "Drill-powered", item_type: "drill_powered" },
  { code: "279", name: "Dry Bath", item_type: "dry_bath" },
  { code: "1252", name: "Drying Bench", item_type: "drying_bench" },
  { code: "304", name: "Duplicator Fordiograph", item_type: "duplicator_fordiograph" },
  { code: "308", name: "Duplicator Offset Print", item_type: "duplicator_offset_print" },
  { code: "284", name: "Dust Vac", item_type: "dust_vac" },
  { code: "461", name: "DVD/VHS  Player", item_type: "dvd_vhs_player" },
  { code: "286", name: "EFTPOS Machine", item_type: "eftpos_machine" },
  { code: "847", name: "Electric Balance", item_type: "electric_balance" },
  { code: "288", name: "Electric Bed/Lift", item_type: "electric_bed_lift" },
  { code: "290", name: "Electric Bench", item_type: "electric_bench" },
  { code: "625", name: "Electric Blanket", item_type: "electric_blanket" },
  { code: "1127", name: "Electric Desk", item_type: "electric_desk" },
  { code: "1353", name: "Electric Door Opener", item_type: "electric_door_opener" },
  { code: "199", name: "Electric Generator", item_type: "electric_generator" },
  { code: "292", name: "Electric Tagger", item_type: "electric_tagger" },
  { code: "1219", name: "Electrophoresis", item_type: "electrophoresis" },
  { code: "296", name: "Electrothermal", item_type: "electrothermal" },
  { code: "1235", name: "Elipar", item_type: "elipar" },
  { code: "1155", name: "Embedding Station", item_type: "embedding_station" },
  { code: "947", name: "Emergency/Exit Light", item_type: "emergency_exit_light" },
  { code: "820", name: "Emeter", item_type: "emeter" },
  { code: "741", name: "Engine Analyser", item_type: "engine_analyser" },
  { code: "432", name: "Engraver", item_type: "engraver" },
  { code: "538", name: "Envelope Machine", item_type: "envelope_machine" },
  { code: "1116", name: "Envirobank", item_type: "envirobank" },
  { code: "164", name: "Equaliser", item_type: "equaliser" },
  { code: "299", name: "Etching Tank", item_type: "etching_tank" },
  { code: "1245", name: "Evaporator Pan", item_type: "evaporator_pan" },
  { code: "302", name: "Exercise Machine", item_type: "exercise_machine" },
  { code: "1073", name: "Extraction System", item_type: "extraction_system" },
  { code: "1199", name: "Extractor", item_type: "extractor" },
  { code: "303", name: "Eye Test/Chart", item_type: "eye_test_chart" },
  { code: "418", name: "Fan Floor/Desk", item_type: "fan_floor_desk" },
  { code: "437", name: "Fax Machine", item_type: "fax_machine" },
  { code: "1400", name: "Fibre Optic Splicer", item_type: "fibre_optic_splicer" },
  { code: "527", name: "File Server", item_type: "file_server" },
  { code: "166", name: "Film Editor", item_type: "film_editor" },
  { code: "1070", name: "Flame Photometer", item_type: "flame_photometer" },
  { code: "671", name: "Flask Shaker", item_type: "flask_shaker" },
  { code: "997", name: "Flex Focus", item_type: "flex_focus" },
  { code: "668", name: "Floatation Machine", item_type: "floatation_machine" },
  { code: "726", name: "Floor Dryer", item_type: "floor_dryer" },
  { code: "140", name: "Floor Polisher", item_type: "floor_polisher" },
  { code: "1216", name: "Flow Cytometer", item_type: "flow_cytometer" },
  { code: "1176", name: "Fluid Warmer", item_type: "fluid_warmer" },
  { code: "557", name: "Fluids Test Bench", item_type: "fluids_test_bench" },
  { code: "1158", name: "Fluorometer", item_type: "fluorometer" },
  { code: "1091", name: "Flutter Meter", item_type: "flutter_meter" },
  { code: "400", name: "Foam cutter", item_type: "foam_cutter" },
  { code: "142", name: "Fog Machine", item_type: "fog_machine" },
  { code: "310", name: "Folder", item_type: "folder" },
  { code: "204", name: "Food Barmix", item_type: "food_barmix" },
  { code: "458", name: "Food Blender", item_type: "food_blender" },
  { code: "588", name: "Food Bowl Cutter", item_type: "food_bowl_cutter" },
  { code: "206", name: "Food Bread Maker", item_type: "food_bread_maker" },
  { code: "596", name: "Food Bread Slicer", item_type: "food_bread_slicer" },
  { code: "619", name: "Food Cabinet", item_type: "food_cabinet" },
  { code: "207", name: "Food Can Opener", item_type: "food_can_opener" },
  { code: "955", name: "Food Chip Tray", item_type: "food_chip_tray" },
  { code: "825", name: "Food Coffee Grinder", item_type: "food_coffee_grinder" },
  { code: "828", name: "Food Coffee Machine", item_type: "food_coffee_machine" },
  { code: "209", name: "Food Crock Pot", item_type: "food_crock_pot" },
  { code: "1171", name: "Food Cupcake Maker", item_type: "food_cupcake_maker" },
  { code: "827", name: "Food Donut Maker", item_type: "food_donut_maker" },
  { code: "622", name: "Food Dough Mixer", item_type: "food_dough_mixer" },
  { code: "211", name: "Food Egg Cooker", item_type: "food_egg_cooker" },
  { code: "213", name: "Food Electric Knife", item_type: "food_electric_knife" },
  { code: "474", name: "Food Frying Pan", item_type: "food_frying_pan" },
  { code: "214", name: "Food Grill", item_type: "food_grill" },
  { code: "587", name: "Food Hand Wrapper", item_type: "food_hand_wrapper" },
  { code: "216", name: "Food Hot Dog Warmer", item_type: "food_hot_dog_warmer" },
  { code: "478", name: "Food Hot Plate", item_type: "food_hot_plate" },
  { code: "218", name: "Food Ice Cream Maker", item_type: "food_ice_cream_maker" },
  { code: "219", name: "Food Jaffle Iron", item_type: "food_jaffle_iron" },
  { code: "479", name: "Food Jug/Kettle", item_type: "food_jug_kettle" },
  { code: "829", name: "Food Juicer", item_type: "food_juicer" },
  { code: "585", name: "Food Knife Sharpener", item_type: "food_knife_sharpener" },
  { code: "950", name: "Food McFlurry Machine", item_type: "food_mcflurry_machine" },
  { code: "222", name: "Food Meat Slicer", item_type: "food_meat_slicer" },
  { code: "419", name: "Food Microwave", item_type: "food_microwave" },
  { code: "1244", name: "Food Milk Frother", item_type: "food_milk_frother" },
  { code: "223", name: "Food Milkshake Maker", item_type: "food_milkshake_maker" },
  { code: "617", name: "Food Mincer/Mixer", item_type: "food_mincer_mixer" },
  { code: "448", name: "Food Mixer", item_type: "food_mixer" },
  { code: "595", name: "Food Pastry Roller", item_type: "food_pastry_roller" },
  { code: "618", name: "Food Pickel Pump", item_type: "food_pickel_pump" },
  { code: "226", name: "Food Pie Maker", item_type: "food_pie_maker" },
  { code: "227", name: "Food Popcorn Machine", item_type: "food_popcorn_machine" },
  { code: "621", name: "Food Pressure Cooker", item_type: "food_pressure_cooker" },
  { code: "240", name: "Food Processor", item_type: "food_processor" },
  { code: "243", name: "Food Rice Cooker", item_type: "food_rice_cooker" },
  { code: "480", name: "Food Sandwich Maker", item_type: "food_sandwich_maker" },
  { code: "245", name: "Food Slushi Machine", item_type: "food_slushi_machine" },
  { code: "590", name: "Food Smoke House", item_type: "food_smoke_house" },
  { code: "248", name: "Food Snow Cone Maker", item_type: "food_snow_cone_maker" },
  { code: "949", name: "Food Sunday Machine", item_type: "food_sunday_machine" },
  { code: "586", name: "Food Tenderiser", item_type: "food_tenderiser" },
  { code: "429", name: "Food Toaster", item_type: "food_toaster" },
  { code: "249", name: "Food Toaster Oven", item_type: "food_toaster_oven" },
  { code: "899", name: "Food Trolley", item_type: "food_trolley" },
  { code: "473", name: "Food Urn", item_type: "food_urn" },
  { code: "251", name: "Food Warmer", item_type: "food_warmer" },
  { code: "252", name: "Food Wok", item_type: "food_wok" },
  { code: "323", name: "Foot Bath", item_type: "foot_bath" },
  { code: "900", name: "Forge", item_type: "forge" },
  { code: "1262", name: "Franking Machine", item_type: "franking_machine" },
  { code: "1364", name: "Freeze Dryer", item_type: "freeze_dryer" },
  { code: "441", name: "Freezer Food", item_type: "freezer_food" },
  { code: "1088", name: "Freq. Meter/Counter", item_type: "freq_meter_counter" },
  { code: "144", name: "Frequency Meter", item_type: "frequency_meter" },
  { code: "1402", name: "Friabilator", item_type: "friabilator" },
  { code: "901", name: "Fume Extractor", item_type: "fume_extractor" },
  { code: "558", name: "Fume Hood/Cabinet", item_type: "fume_hood_cabinet" },
  { code: "670", name: "Furnace", item_type: "furnace" },
  { code: "307", name: "Fxd Bandsaw", item_type: "fxd_bandsaw" },
  { code: "318", name: "Fxd Brobo Saw", item_type: "fxd_brobo_saw" },
  { code: "319", name: "Fxd Buffer", item_type: "fxd_buffer" },
  { code: "124", name: "Fxd Circular Saw", item_type: "fxd_circular_saw" },
  { code: "321", name: "Fxd Deep Fryer", item_type: "fxd_deep_fryer" },
  { code: "466", name: "Fxd Dishwasher", item_type: "fxd_dishwasher" },
  { code: "529", name: "Fxd Drill", item_type: "fxd_drill" },
  { code: "198", name: "Fxd Drill 3phase", item_type: "fxd_drill_3phase" },
  { code: "194", name: "Fxd Drill Mill", item_type: "fxd_drill_mill" },
  { code: "200", name: "Fxd Dryer Clothes", item_type: "fxd_dryer_clothes" },
  { code: "202", name: "Fxd Dust Extractor", item_type: "fxd_dust_extractor" },
  { code: "203", name: "Fxd Exhaust Fan", item_type: "fxd_exhaust_fan" },
  { code: "205", name: "Fxd Grinder", item_type: "fxd_grinder" },
  { code: "208", name: "Fxd Hack Saw", item_type: "fxd_hack_saw" },
  { code: "210", name: "Fxd Hand Dryer", item_type: "fxd_hand_dryer" },
  { code: "212", name: "Fxd Key Cutter", item_type: "fxd_key_cutter" },
  { code: "403", name: "Fxd Kiln", item_type: "fxd_kiln" },
  { code: "217", name: "Fxd Lighting Panel", item_type: "fxd_lighting_panel" },
  { code: "220", name: "Fxd Metal Folder", item_type: "fxd_metal_folder" },
  { code: "221", name: "Fxd Milling Machine", item_type: "fxd_milling_machine" },
  { code: "436", name: "Fxd Oven Food", item_type: "fxd_oven_food" },
  { code: "118", name: "Fxd Photo Developer", item_type: "fxd_photo_developer" },
  { code: "487", name: "Fxd Photo Enlarger", item_type: "fxd_photo_enlarger" },
  { code: "435", name: "Fxd Pie Oven/Warmer", item_type: "fxd_pie_oven_warmer" },
  { code: "119", name: "Fxd Plastic Moulder", item_type: "fxd_plastic_moulder" },
  { code: "121", name: "Fxd Pottery Wheel", item_type: "fxd_pottery_wheel" },
  { code: "116", name: "Fxd Range Hood", item_type: "fxd_range_hood" },
  { code: "530", name: "Fxd Sander Bench", item_type: "fxd_sander_bench" },
  { code: "340", name: "Fxd Sander Disc", item_type: "fxd_sander_disc" },
  { code: "128", name: "Fxd Stove Cooking", item_type: "fxd_stove_cooking" },
  { code: "408", name: "Fxd Thicknesser/Planer", item_type: "fxd_thicknesser_planer" },
  { code: "409", name: "Fxd Vending Machine", item_type: "fxd_vending_machine" },
  { code: "134", name: "Fxd Washing Machine", item_type: "fxd_washing_machine" },
  { code: "136", name: "Fxd Water Heater", item_type: "fxd_water_heater" },
  { code: "139", name: "Fxd Wood/Metal Lathe", item_type: "fxd_wood_metal_lathe" },
  { code: "938", name: "Games Console", item_type: "games_console" },
  { code: "723", name: "Gas Analyser", item_type: "gas_analyser" },
  { code: "1065", name: "Gas Generator", item_type: "gas_generator" },
  { code: "146", name: "Gas Igniters", item_type: "gas_igniters" },
  { code: "149", name: "GAT", item_type: "gat" },
  { code: "167", name: "Geiger Counter", item_type: "geiger_counter" },
  { code: "325", name: "Gerni/Gurney", item_type: "gerni_gurney" },
  { code: "552", name: "Glass Washer", item_type: "glass_washer" },
  { code: "905", name: "Glasswear Dryer", item_type: "glasswear_dryer" },
  { code: "784", name: "Greaseater", item_type: "greaseater" },
  { code: "757", name: "Grinder Valve Seat", item_type: "grinder_valve_seat" },
  { code: "1290", name: "Guillotine", item_type: "guillotine" },
  { code: "837", name: "Hair Clippers", item_type: "hair_clippers" },
  { code: "328", name: "Hair Dryer/Straightener", item_type: "hair_dryer_straightener" },
  { code: "329", name: "Hand Shear", item_type: "hand_shear" },
  { code: "1003", name: "HARP", item_type: "harp" },
  { code: "996", name: "Harshaw", item_type: "harshaw" },
  { code: "1114", name: "Hat Steamer", item_type: "hat_steamer" },
  { code: "150", name: "Hearing Loop Driver", item_type: "hearing_loop_driver" },
  { code: "332", name: "Heat Gun", item_type: "heat_gun" },
  { code: "402", name: "Heat N Grow", item_type: "heat_n_grow" },
  { code: "113", name: "Heater Radiant Floor", item_type: "heater_radiant_floor" },
  { code: "117", name: "Heater Radiant Wall", item_type: "heater_radiant_wall" },
  { code: "169", name: "Heating Mantle", item_type: "heating_mantle" },
  { code: "577", name: "Heating Vat", item_type: "heating_vat" },
  { code: "326", name: "Hedge Trimmer", item_type: "hedge_trimmer" },
  { code: "680", name: "Hoist", item_type: "hoist" },
  { code: "312", name: "Hole Punch", item_type: "hole_punch" },
  { code: "1034", name: "Hopper", item_type: "hopper" },
  { code: "482", name: "Hot Glue Gun", item_type: "hot_glue_gun" },
  { code: "848", name: "Hot Plate / Stirrer", item_type: "hot_plate_stirrer" },
  { code: "1253", name: "Hot Water System", item_type: "hot_water_system" },
  { code: "1029", name: "Hot Wire Cutter", item_type: "hot_wire_cutter" },
  { code: "936", name: "Humidifier", item_type: "humidifier" },
  { code: "953", name: "Hydraulic Power Unit", item_type: "hydraulic_power_unit" },
  { code: "767", name: "Hydro Bath", item_type: "hydro_bath" },
  { code: "979", name: "Hydrocollator", item_type: "hydrocollator" },
  { code: "152", name: "ICE Machine", item_type: "ice_machine" },
  { code: "1157", name: "ICP Machine", item_type: "icp_machine" },
  { code: "981", name: "IEC Lead  Bio Med", item_type: "iec_lead_bio_med" },
  { code: "1058", name: "IEC Lead 20 AMP", item_type: "iec_lead_20_amp" },
  { code: "888", name: "Ignition Simulator", item_type: "ignition_simulator" },
  { code: "153", name: "Image Maker", item_type: "image_maker" },
  { code: "1193", name: "Imaging System", item_type: "imaging_system" },
  { code: "662", name: "Impact Wrench", item_type: "impact_wrench" },
  { code: "1009", name: "Incinerator", item_type: "incinerator" },
  { code: "170", name: "Incubator bench type", item_type: "incubator_bench_type" },
  { code: "972", name: "Industrial Stapler", item_type: "industrial_stapler" },
  { code: "1247", name: "Infant Warmer", item_type: "infant_warmer" },
  { code: "171", name: "Infra Red Lamp", item_type: "infra_red_lamp" },
  { code: "769", name: "Infusion Pump", item_type: "infusion_pump" },
  { code: "1156", name: "Injector", item_type: "injector" },
  { code: "770", name: "Injector Cleaner", item_type: "injector_cleaner" },
  { code: "717", name: "Injector Tester", item_type: "injector_tester" },
  { code: "1195", name: "Innoculator", item_type: "innoculator" },
  { code: "1064", name: "Insinkerator", item_type: "insinkerator" },
  { code: "469", name: "Intercom/PA System", item_type: "intercom_pa_system" },
  { code: "154", name: "Irrigation", item_type: "irrigation" },
  { code: "902", name: "IV Drip Machine", item_type: "iv_drip_machine" },
  { code: "1131", name: "Jack Hammer", item_type: "jack_hammer" },
  { code: "791", name: "Jump Starter", item_type: "jump_starter" },
  { code: "592", name: "Keno Machine", item_type: "keno_machine" },
  { code: "404", name: "Label Maker (Dymo)", item_type: "label_maker_dymo" },
  { code: "439", name: "Laminator", item_type: "laminator" },
  { code: "155", name: "Lamp - Fairy Lights", item_type: "lamp_fairy_lights" },
  { code: "257", name: "Lamp Holder", item_type: "lamp_holder" },
  { code: "823", name: "Lamp Lead with light", item_type: "lamp_lead_with_light" },
  { code: "109", name: "Lamp M/Scope 12V", item_type: "lamp_m_scope_12v" },
  { code: "110", name: "Lamp M/Scope 240V", item_type: "lamp_m_scope_240v" },
  { code: "174", name: "Lamp M/Scope Substage", item_type: "lamp_m_scope_substage" },
  { code: "821", name: "Lamp-Desk/Spot 12V", item_type: "lamp_desk_spot_12v" },
  { code: "414", name: "Lamp-Desk/Spot 240V", item_type: "lamp_desk_spot_240v" },
  { code: "822", name: "Lamp-Desk/Spot 6V", item_type: "lamp_desk_spot_6v" },
  { code: "1121", name: "Lamp-Flood 240Vglobe", item_type: "lamp_flood_240vglobe" },
  { code: "375", name: "Lamp-Fluoro 240V", item_type: "lamp_fluoro_240v" },
  { code: "274", name: "Language Master", item_type: "language_master" },
  { code: "449", name: "Laptop", item_type: "laptop" },
  { code: "1296", name: "Laptop Charger", item_type: "laptop_charger" },
  { code: "1297", name: "Laptop Dock", item_type: "laptop_dock" },
  { code: "876", name: "Laptop Dock Station", item_type: "laptop_dock_station" },
  { code: "175", name: "Laser", item_type: "laser" },
  { code: "868", name: "Laser Engraver/Cutter", item_type: "laser_engraver_cutter" },
  { code: "835", name: "Lawn Mower", item_type: "lawn_mower" },
  { code: "424", name: "Lead Extension", item_type: "lead_extension" },
  { code: "446", name: "Lead Figure 8", item_type: "lead_figure_8" },
  { code: "413", name: "Lead IEC", item_type: "lead_iec" },
  { code: "1050", name: "Leakage Tester", item_type: "leakage_tester" },
  { code: "1335", name: "Leather Splitter", item_type: "leather_splitter" },
  { code: "1150", name: "Lectropol", item_type: "lectropol" },
  { code: "1333", name: "Lecturn", item_type: "lecturn" },
  { code: "539", name: "Letter Folder", item_type: "letter_folder" },
  { code: "178", name: "Light Box Control", item_type: "light_box_control" },
  { code: "275", name: "Light Dimmer", item_type: "light_dimmer" },
  { code: "277", name: "Light Disco", item_type: "light_disco" },
  { code: "884", name: "Light Halogen 1.5K", item_type: "light_halogen_1_5k" },
  { code: "879", name: "Light Halogen 10k", item_type: "light_halogen_10k" },
  { code: "877", name: "Light Halogen 500", item_type: "light_halogen_500" },
  { code: "928", name: "Lights Fluoro", item_type: "lights_fluoro" },
  { code: "881", name: "Lights Fluoro 55W", item_type: "lights_fluoro_55w" },
  { code: "836", name: "Line Trimmer", item_type: "line_trimmer" },
  { code: "667", name: "Mag Seperator/Flow Meter", item_type: "mag_seperator_flow_meter" },
  { code: "280", name: "Magna Light", item_type: "magna_light" },
  { code: "176", name: "Magnetic Stirrer", item_type: "magnetic_stirrer" },
  { code: "771", name: "Magneto Tester", item_type: "magneto_tester" },
  { code: "281", name: "Magnifier", item_type: "magnifier" },
  { code: "283", name: "Massager", item_type: "massager" },
  { code: "285", name: "Maymist", item_type: "maymist" },
  { code: "569", name: "Melter", item_type: "melter" },
  { code: "673", name: "Melting Point Apperatus", item_type: "melting_point_apperatus" },
  { code: "772", name: "Metal Cutter", item_type: "metal_cutter" },
  { code: "807", name: "Metal Halide Lamp", item_type: "metal_halide_lamp" },
  { code: "287", name: "Microfiche", item_type: "microfiche" },
  { code: "911", name: "Microlight", item_type: "microlight" },
  { code: "182", name: "Microphone", item_type: "microphone" },
  { code: "878", name: "Microwave Radiation", item_type: "microwave_radiation" },
  { code: "177", name: "Millikan's Oil Drop Expt", item_type: "millikan_oil_drop_expt" },
  { code: "564", name: "Milling Machine/Table", item_type: "milling_machine_table" },
  { code: "291", name: "Mirror Ball", item_type: "mirror_ball" },
  { code: "184", name: "Mixing Console", item_type: "mixing_console" },
  { code: "293", name: "Mobile", item_type: "mobile" },
  { code: "370", name: "Modem", item_type: "modem" },
  { code: "295", name: "Module", item_type: "module" },
  { code: "416", name: "Monitor", item_type: "monitor" },
  { code: "333", name: "Mortising Machine", item_type: "mortising_machine" },
  { code: "297", name: "Motor 240v", item_type: "motor_240v" },
  { code: "1026", name: "Multimeter", item_type: "multimeter" },
  { code: "224", name: "Musicolour", item_type: "musicolour" },
  { code: "785", name: "Must Pump", item_type: "must_pump" },
  { code: "334", name: "Nail Gun", item_type: "nail_gun" },
  { code: "355", name: "Nebuliser", item_type: "nebuliser" },
  { code: "371", name: "Network Power Supply", item_type: "network_power_supply" },
  { code: "335", name: "Nibbler", item_type: "nibbler" },
  { code: "1128", name: "Off Charge Cable", item_type: "off_charge_cable" },
  { code: "623", name: "Oil Burner", item_type: "oil_burner" },
  { code: "676", name: "Oil Content Analyser", item_type: "oil_content_analyser" },
  { code: "966", name: "Oil Distiller", item_type: "oil_distiller" },
  { code: "967", name: "Oil Filter", item_type: "oil_filter" },
  { code: "968", name: "Oil Oven", item_type: "oil_oven" },
  { code: "624", name: "Oil Vapourizer", item_type: "oil_vapourizer" },
  { code: "774", name: "Oil Vat", item_type: "oil_vat" },
  { code: "1340", name: "Orbital Shaker", item_type: "orbital_shaker" },
  { code: "1023", name: "Orthopaedic Saw", item_type: "orthopaedic_saw" },
  { code: "883", name: "Oscillator", item_type: "oscillator" },
  { code: "253", name: "Oscilloscope(CRO)", item_type: "oscilloscope_cro" },
  { code: "1274", name: "Osmometer", item_type: "osmometer" },
  { code: "1130", name: "Other - Car Hoist", item_type: "other_car_hoist" },
  { code: "532", name: "Other (Specify)", item_type: "other_specify" },
  { code: "427", name: "Overhead Projector", item_type: "overhead_projector" },
  { code: "356", name: "Overlocker Machine", item_type: "overlocker_machine" },
  { code: "830", name: "Oxygen Pump", item_type: "oxygen_pump" },
  { code: "960", name: "Page Writer", item_type: "page_writer" },
  { code: "336", name: "Paint Gun", item_type: "paint_gun" },
  { code: "337", name: "Paint Mixer", item_type: "paint_mixer" },
  { code: "560", name: "Paint Stripper", item_type: "paint_stripper" },
  { code: "567", name: "Paper Feeder", item_type: "paper_feeder" },
  { code: "1289", name: "Paper Shaker", item_type: "paper_shaker" },
  { code: "442", name: "Paper Shredder", item_type: "paper_shredder" },
  { code: "475", name: "Paper Stapler", item_type: "paper_stapler" },
  { code: "406", name: "Paper Warmer", item_type: "paper_warmer" },
  { code: "714", name: "Parts Washer", item_type: "parts_washer" },
  { code: "447", name: "Patch Lead 240V", item_type: "patch_lead_240v" },
  { code: "895", name: "Patchboard", item_type: "patchboard" },
  { code: "1090", name: "Pattern Generator", item_type: "pattern_generator" },
  { code: "909", name: "PC - IEC Lead", item_type: "pc_iec_lead" },
  { code: "871", name: "PC Y-lead", item_type: "pc_y_lead" },
  { code: "322", name: "PC/TV Trolley", item_type: "pc_tv_trolley" },
  { code: "1177", name: "PCA Pump", item_type: "pca_pump" },
  { code: "1200", name: "PCR Machine", item_type: "pcr_machine" },
  { code: "1059", name: "PDA Detector", item_type: "pda_detector" },
  { code: "882", name: "Pelican Torch Charger", item_type: "pelican_torch_charger" },
  { code: "1299", name: "Pencil Grinder", item_type: "pencil_grinder" },
  { code: "476", name: "Pencil Sharpener", item_type: "pencil_sharpener" },
  { code: "565", name: "Phase Shifter", item_type: "phase_shifter" },
  { code: "578", name: "Phone Charger", item_type: "phone_charger" },
  { code: "477", name: "Phone/PABX", item_type: "phone_pabx" },
  { code: "809", name: "Photo Wash Tank", item_type: "photo_wash_tank" },
  { code: "434", name: "Photocopier", item_type: "photocopier" },
  { code: "954", name: "Photocorder", item_type: "photocorder" },
  { code: "1062", name: "Photodiode Array", item_type: "photodiode_array" },
  { code: "1151", name: "Photometer", item_type: "photometer" },
  { code: "932", name: "Physio Equipment", item_type: "physio_equipment" },
  { code: "470", name: "Piano/Keyboard", item_type: "piano_keyboard" },
  { code: "1304", name: "Pipe Threader/Bender", item_type: "pipe_threader_bender" },
  { code: "1203", name: "Pipetting Machine", item_type: "pipetting_machine" },
  { code: "1115", name: "Pittsburgh Machine", item_type: "pittsburgh_machine" },
  { code: "994", name: "PIW Multidos", item_type: "piw_multidos" },
  { code: "338", name: "Planer Wood", item_type: "planer_wood" },
  { code: "660", name: "Plasma Cutter", item_type: "plasma_cutter" },
  { code: "935", name: "Plaster Cutter", item_type: "plaster_cutter" },
  { code: "189", name: "Plaster Pump", item_type: "plaster_pump" },
  { code: "339", name: "Plastic Bender", item_type: "plastic_bender" },
  { code: "1374", name: "Plate Warmer", item_type: "plate_warmer" },
  { code: "1275", name: "Platelet Reciprocator", item_type: "platelet_reciprocator" },
  { code: "1183", name: "Platform Rocker", item_type: "platform_rocker" },
  { code: "1179", name: "Pneumatic Solenoid", item_type: "pneumatic_solenoid" },
  { code: "1113", name: "Pneumopulse Machine", item_type: "pneumopulse_machine" },
  { code: "865", name: "PNom - IEC Lead", item_type: "pnom_iec_lead" },
  { code: "864", name: "PNom - PC/TV Trolley", item_type: "pnom_pc_tv_trolley" },
  { code: "853", name: "PNom Comms Cab/Hub", item_type: "pnom_comms_cab_hub" },
  { code: "854", name: "PNom Computer (CPU)", item_type: "pnom_computer_cpu" },
  { code: "856", name: "PNom File Server", item_type: "pnom_file_server" },
  { code: "855", name: "PNom Hard Drive", item_type: "pnom_hard_drive" },
  { code: "857", name: "PNom Laptop", item_type: "pnom_laptop" },
  { code: "858", name: "PNom Modem", item_type: "pnom_modem" },
  { code: "859", name: "PNom Monitor", item_type: "pnom_monitor" },
  { code: "860", name: "PNom Network P-Supply", item_type: "pnom_network_p_supply" },
  { code: "861", name: "PNom Printer", item_type: "pnom_printer" },
  { code: "862", name: "PNom Scanner", item_type: "pnom_scanner" },
  { code: "863", name: "PNom UPS", item_type: "pnom_ups" },
  { code: "872", name: "PNom Y-lead", item_type: "pnom_y_lead" },
  { code: "591", name: "Poker Machine", item_type: "poker_machine" },
  { code: "190", name: "Polariser", item_type: "polariser" },
  { code: "675", name: "Polisher", item_type: "polisher" },
  { code: "991", name: "Port Hot Tray", item_type: "port_hot_tray" },
  { code: "1126", name: "Porta Filter", item_type: "porta_filter" },
  { code: "999", name: "Portable X-Ray", item_type: "portable_x_ray" },
  { code: "731", name: "Power Steamer", item_type: "power_steamer" },
  { code: "1389", name: "Power Supply Lead", item_type: "power_supply_lead" },
  { code: "111", name: "Power Supply(Tx)", item_type: "power_supply_tx" },
  { code: "420", name: "Powerboard", item_type: "powerboard" },
  { code: "361", name: "PowerBox", item_type: "powerbox" },
  { code: "851", name: "PowerSupply/PowerBox", item_type: "powersupply_powerbox" },
  { code: "362", name: "Press", item_type: "press" },
  { code: "728", name: "Pressure Sprayer", item_type: "pressure_sprayer" },
  { code: "724", name: "Pressure Tester", item_type: "pressure_tester" },
  { code: "1337", name: "Print Mate", item_type: "print_mate" },
  { code: "417", name: "Printer", item_type: "printer" },
  { code: "650", name: "Profile Cutter", item_type: "profile_cutter" },
  { code: "568", name: "Program Controller", item_type: "program_controller" },
  { code: "162", name: "Projector", item_type: "projector" },
  { code: "1080", name: "Protocol", item_type: "protocol" },
  { code: "108", name: "Pump", item_type: "pump" },
  { code: "840", name: "Pump Bilge", item_type: "pump_bilge" },
  { code: "572", name: "Pump Cooling", item_type: "pump_cooling" },
  { code: "363", name: "Pump Filter", item_type: "pump_filter" },
  { code: "841", name: "Pump Pool", item_type: "pump_pool" },
  { code: "842", name: "Pump Water", item_type: "pump_water" },
  { code: "364", name: "Putting Partner", item_type: "putting_partner" },
  { code: "1368", name: "Quickscan", item_type: "quickscan" },
  { code: "1002", name: "Rack System", item_type: "rack_system" },
  { code: "721", name: "Rattle Gun", item_type: "rattle_gun" },
  { code: "869", name: "RCD", item_type: "rcd" },
  { code: "1020", name: "RCD Portable Push", item_type: "rcd_portable_push" },
  { code: "1019", name: "RCD Portable Timed", item_type: "rcd_portable_timed" },
  { code: "977", name: "RCD Push Button", item_type: "rcd_push_button" },
  { code: "526", name: "RCD Test - Timed", item_type: "rcd_test_timed" },
  { code: "844", name: "RCD with lead", item_type: "rcd_with_lead" },
  { code: "845", name: "RCD with powerboard", item_type: "rcd_with_powerboard" },
  { code: "365", name: "Reader", item_type: "reader" },
  { code: "444", name: "Receipt Machine", item_type: "receipt_machine" },
  { code: "366", name: "Receiver", item_type: "receiver" },
  { code: "225", name: "Record Player", item_type: "record_player" },
  { code: "156", name: "Recorder", item_type: "recorder" },
  { code: "421", name: "Refrigerator", item_type: "refrigerator" },
  { code: "157", name: "Register", item_type: "register" },
  { code: "571", name: "Regulator", item_type: "regulator" },
  { code: "158", name: "Remote", item_type: "remote" },
  { code: "525", name: "Repaired", item_type: "repaired" },
  { code: "1215", name: "Reservoir", item_type: "reservoir" },
  { code: "641", name: "Roller", item_type: "roller" },
  { code: "1129", name: "Rope Cutter", item_type: "rope_cutter" },
  { code: "1173", name: "Rotary Tool", item_type: "rotary_tool" },
  { code: "483", name: "Router", item_type: "router" },
  { code: "546", name: "Salad Bar", item_type: "salad_bar" },
  { code: "941", name: "Salamander", item_type: "salamander" },
  { code: "1067", name: "Sampler", item_type: "sampler" },
  { code: "327", name: "Sand blaster", item_type: "sand_blaster" },
  { code: "357", name: "Sand Mixer", item_type: "sand_mixer" },
  { code: "484", name: "Sander", item_type: "sander" },
  { code: "192", name: "Sander Disc", item_type: "sander_disc" },
  { code: "341", name: "Sander Orbital", item_type: "sander_orbital" },
  { code: "342", name: "Saw Circular", item_type: "saw_circular" },
  { code: "343", name: "Saw Compound", item_type: "saw_compound" },
  { code: "344", name: "Saw Drop", item_type: "saw_drop" },
  { code: "407", name: "Saw Drop and Slide", item_type: "saw_drop_and_slide" },
  { code: "485", name: "Saw Jig", item_type: "saw_jig" },
  { code: "776", name: "Saw Metal", item_type: "saw_metal" },
  { code: "346", name: "Saw Mitre", item_type: "saw_mitre" },
  { code: "347", name: "Saw Radial Arm", item_type: "saw_radial_arm" },
  { code: "661", name: "Saw Saber", item_type: "saw_saber" },
  { code: "348", name: "Saw Scroll", item_type: "saw_scroll" },
  { code: "358", name: "Scales", item_type: "scales" },
  { code: "450", name: "Scanner", item_type: "scanner" },
  { code: "839", name: "Screw Driver", item_type: "screw_driver" },
  { code: "1361", name: "Sealing Machine", item_type: "sealing_machine" },
  { code: "488", name: "Security Scanner", item_type: "security_scanner" },
  { code: "553", name: "Security Sensor", item_type: "security_sensor" },
  { code: "794", name: "Semi Conductor Tester", item_type: "semi_conductor_tester" },
  { code: "489", name: "Sensitiser", item_type: "sensitiser" },
  { code: "490", name: "Sensor", item_type: "sensor" },
  { code: "674", name: "Seperator", item_type: "seperator" },
  { code: "491", name: "Server", item_type: "server" },
  { code: "457", name: "Sewing Machine", item_type: "sewing_machine" },
  { code: "742", name: "Shaft Location Control", item_type: "shaft_location_control" },
  { code: "1323", name: "Shaker", item_type: "shaker" },
  { code: "892", name: "Shears/Scissor", item_type: "shears_scissor" },
  { code: "573", name: "Sign", item_type: "sign" },
  { code: "725", name: "Sign Cutter", item_type: "sign_cutter" },
  { code: "179", name: "Signal Generator", item_type: "signal_generator" },
  { code: "743", name: "Signal Tracer", item_type: "signal_tracer" },
  { code: "1008", name: "Slicer", item_type: "slicer" },
  { code: "1189", name: "Slide Cutter", item_type: "slide_cutter" },
  { code: "1132", name: "Slide Drying Bench", item_type: "slide_drying_bench" },
  { code: "1261", name: "Slide Processor", item_type: "slide_processor" },
  { code: "229", name: "Slide Projector", item_type: "slide_projector" },
  { code: "562", name: "Slow Cooker", item_type: "slow_cooker" },
  { code: "952", name: "Smart Board", item_type: "smart_board" },
  { code: "359", name: "Smoke Machine", item_type: "smoke_machine" },
  { code: "1124", name: "Smoke Machine", item_type: "smoke_machine" },
  { code: "180", name: "Sodium Vapour Lamp", item_type: "sodium_vapour_lamp" },
  { code: "832", name: "Soldering Iron", item_type: "soldering_iron" },
  { code: "1276", name: "Solenoid", item_type: "solenoid" },
  { code: "1049", name: "Soluscope", item_type: "soluscope" },
  { code: "1060", name: "Solvent Manager", item_type: "solvent_manager" },
  { code: "1197", name: "Solvent Recycler", item_type: "solvent_recycler" },
  { code: "1279", name: "Sonicator", item_type: "sonicator" },
  { code: "1288", name: "Sorter", item_type: "sorter" },
  { code: "777", name: "Sorting Machine", item_type: "sorting_machine" },
  { code: "230", name: "Sound Mixer", item_type: "sound_mixer" },
  { code: "536", name: "Soup Pot", item_type: "soup_pot" },
  { code: "933", name: "Spa", item_type: "spa" },
  { code: "115", name: "Space Heater Oil", item_type: "space_heater_oil" },
  { code: "528", name: "Space/Fan Heater", item_type: "space_fan_heater" },
  { code: "716", name: "Spark Plug Tester", item_type: "spark_plug_tester" },
  { code: "463", name: "Speaker", item_type: "speaker" },
  { code: "181", name: "Spectra Lamp", item_type: "spectra_lamp" },
  { code: "524", name: "Spectrometer", item_type: "spectrometer" },
  { code: "810", name: "Speed Indicator", item_type: "speed_indicator" },
  { code: "1332", name: "Splash Vac", item_type: "splash_vac" },
  { code: "1037", name: "Splinting Pan", item_type: "splinting_pan" },
  { code: "492", name: "Splitters", item_type: "splitters" },
  { code: "493", name: "Sprayer", item_type: "sprayer" },
  { code: "494", name: "Stage Lights", item_type: "stage_lights" },
  { code: "1100", name: "Stainer", item_type: "stainer" },
  { code: "495", name: "Standing Frame", item_type: "standing_frame" },
  { code: "496", name: "Static Generator", item_type: "static_generator" },
  { code: "727", name: "Steam Cleaner", item_type: "steam_cleaner" },
  { code: "545", name: "Steamer Food", item_type: "steamer_food" },
  { code: "850", name: "Steriliser", item_type: "steriliser" },
  { code: "1358", name: "Stimulator", item_type: "stimulator" },
  { code: "497", name: "Stirrer", item_type: "stirrer" },
  { code: "1056", name: "Stomacher 400", item_type: "stomacher_400" },
  { code: "498", name: "Stop/Start Station", item_type: "stop_start_station" },
  { code: "499", name: "Stream watch", item_type: "stream_watch" },
  { code: "183", name: "Stroboscope", item_type: "stroboscope" },
  { code: "232", name: "Subwoofer", item_type: "subwoofer" },
  { code: "1243", name: "Suction Unit", item_type: "suction_unit" },
  { code: "1188", name: "Suspension Mixer", item_type: "suspension_mixer" },
  { code: "755", name: "Switch", item_type: "switch" },
  { code: "779", name: "Syncro Facer", item_type: "syncro_facer" },
  { code: "1178", name: "Syringe Pump", item_type: "syringe_pump" },
  { code: "1255", name: "Tablet Imprest", item_type: "tablet_imprest" },
  { code: "500", name: "Tank", item_type: "tank" },
  { code: "561", name: "Tanning Equipment", item_type: "tanning_equipment" },
  { code: "744", name: "Teletex Decoder", item_type: "teletex_decoder" },
  { code: "425", name: "Television", item_type: "television" },
  { code: "501", name: "Temp Control", item_type: "temp_control" },
  { code: "969", name: "Temperature Tester", item_type: "temperature_tester" },
  { code: "745", name: "Test Panel", item_type: "test_panel" },
  { code: "910", name: "Test Tube Rotator", item_type: "test_tube_rotator" },
  { code: "739", name: "Tester Diode", item_type: "tester_diode" },
  { code: "786", name: "Tester PH", item_type: "tester_ph" },
  { code: "1018", name: "Thermal Machine", item_type: "thermal_machine" },
  { code: "983", name: "Thermofilm", item_type: "thermofilm" },
  { code: "970", name: "Thermographic Scan", item_type: "thermographic_scan" },
  { code: "502", name: "Thermometer", item_type: "thermometer" },
  { code: "672", name: "Thermostat Control", item_type: "thermostat_control" },
  { code: "556", name: "Ticket Printer", item_type: "ticket_printer" },
  { code: "107", name: "Timer", item_type: "timer" },
  { code: "1287", name: "Tissue Processor", item_type: "tissue_processor" },
  { code: "1098", name: "Titrator Meter", item_type: "titrator_meter" },
  { code: "833", name: "Tool Sharpener", item_type: "tool_sharpener" },
  { code: "908", name: "TopPan Balance", item_type: "top_pan_balance" },
  { code: "503", name: "Torch", item_type: "torch" },
  { code: "593", name: "Touch Screen", item_type: "touch_screen" },
  { code: "541", name: "Transcriber", item_type: "transcriber" },
  { code: "1192", name: "Transfer System", item_type: "transfer_system" },
  { code: "428", name: "Transformer", item_type: "transformer" },
  { code: "978", name: "Tray Sealer", item_type: "tray_sealer" },
  { code: "504", name: "Tri Mode", item_type: "tri_mode" },
  { code: "880", name: "Triac Control", item_type: "triac_control" },
  { code: "505", name: "Trimmer", item_type: "trimmer" },
  { code: "186", name: "Triode Demonstration", item_type: "triode_demonstration" },
  { code: "506", name: "Triton", item_type: "triton" },
  { code: "1256", name: "Tube Conditioner", item_type: "tube_conditioner" },
  { code: "1078", name: "Turbidity Meter", item_type: "turbidity_meter" },
  { code: "574", name: "Turbo Dryer", item_type: "turbo_dryer" },
  { code: "507", name: "TV Booster", item_type: "tv_booster" },
  { code: "746", name: "TV IF Modulator", item_type: "tv_if_modulator" },
  { code: "747", name: "TV Pattern Generator", item_type: "tv_pattern_generator" },
  { code: "547", name: "TV Sweep Generator", item_type: "tv_sweep_generator" },
  { code: "233", name: "TV/VCR", item_type: "tv_vcr" },
  { code: "898", name: "Two Way Radio", item_type: "two_way_radio" },
  { code: "445", name: "Typewriter", item_type: "typewriter" },
  { code: "718", name: "Tyre Changer", item_type: "tyre_changer" },
  { code: "1232", name: "Ultramat", item_type: "ultramat" },
  { code: "722", name: "Ultrasonic Cleaner", item_type: "ultrasonic_cleaner" },
  { code: "453", name: "UPS", item_type: "ups" },
  { code: "1329", name: "Urised", item_type: "urised" },
  { code: "1228", name: "Uroflow", item_type: "uroflow" },
  { code: "1052", name: "Utensil Warmer", item_type: "utensil_warmer" },
  { code: "849", name: "UV Lamp", item_type: "uv_lamp" },
  { code: "1054", name: "Vaccine Fridge", item_type: "vaccine_fridge" },
  { code: "756", name: "Vacuum Breaker", item_type: "vacuum_breaker" },
  { code: "120", name: "Vacuum Cleaner", item_type: "vacuum_cleaner" },
  { code: "187", name: "Vacuum Pump", item_type: "vacuum_pump" },
  { code: "544", name: "Vacuum Sealer", item_type: "vacuum_sealer" },
  { code: "750", name: "Valve Refacer", item_type: "valve_refacer" },
  { code: "715", name: "Valve Refacer", item_type: "valve_refacer" },
  { code: "570", name: "Valve Tube Tester", item_type: "valve_tube_tester" },
  { code: "188", name: "Van De Graaff", item_type: "van_de_graaff" },
  { code: "1201", name: "Vaporizer", item_type: "vaporizer" },
  { code: "1194", name: "Ventilator", item_type: "ventilator" },
  { code: "509", name: "Vibrator", item_type: "vibrator" },
  { code: "235", name: "Video Camera", item_type: "video_camera" },
  { code: "237", name: "Video Commander", item_type: "video_commander" },
  { code: "816", name: "Video Conf. Equip", item_type: "video_conf_equip" },
  { code: "510", name: "Viewer", item_type: "viewer" },
  { code: "1366", name: "Viscometer", item_type: "viscometer" },
  { code: "944", name: "Visual Only", item_type: "visual_only" },
  { code: "1102", name: "Volt Meter", item_type: "volt_meter" },
  { code: "824", name: "Volt Slider", item_type: "volt_slider" },
  { code: "543", name: "Voltage Regulator", item_type: "voltage_regulator" },
  { code: "758", name: "Voltage Selector", item_type: "voltage_selector" },
  { code: "906", name: "Vortex Mixer", item_type: "vortex_mixer" },
  { code: "904", name: "W/P Powerboard", item_type: "w_p_powerboard" },
  { code: "1326", name: "Warming Tray", item_type: "warming_tray" },
  { code: "511", name: "washer", item_type: "washer" },
  { code: "512", name: "Washing Pan", item_type: "washing_pan" },
  { code: "513", name: "Water Bath", item_type: "water_bath" },
  { code: "514", name: "Water Blaster", item_type: "water_blaster" },
  { code: "515", name: "Water Cooler", item_type: "water_cooler" },
  { code: "516", name: "Water Filter", item_type: "water_filter" },
  { code: "517", name: "Water Ornament", item_type: "water_ornament" },
  { code: "1123", name: "Water Pump", item_type: "water_pump" },
  { code: "410", name: "Water Purifier/Still", item_type: "water_purifier_still" },
  { code: "360", name: "Wave Machine", item_type: "wave_machine" },
  { code: "677", name: "Weather Station", item_type: "weather_station" },
  { code: "350", name: "Welder", item_type: "welder" },
  { code: "351", name: "Welder MIG", item_type: "welder_mig" },
  { code: "886", name: "Welder Plastic", item_type: "welder_plastic" },
  { code: "352", name: "Welder Spot", item_type: "welder_spot" },
  { code: "353", name: "Welder TIG", item_type: "welder_tig" },
  { code: "719", name: "Wheel Balancer", item_type: "wheel_balancer" },
  { code: "518", name: "White Board Interactive", item_type: "white_board_interactive" },
  { code: "852", name: "White Board Mobile", item_type: "white_board_mobile" },
  { code: "535", name: "White Noise Generator", item_type: "white_noise_generator" },
  { code: "294", name: "Whiteboard Fixed", item_type: "whiteboard_fixed" },
  { code: "519", name: "Winch Back Board", item_type: "winch_back_board" },
  { code: "354", name: "Wood burner/engraver", item_type: "wood_burner_engraver" },
  { code: "1125", name: "Wood Plane", item_type: "wood_plane" },
  { code: "520", name: "World Map", item_type: "world_map" },
  { code: "665", name: "X-ray Control Unit", item_type: "x_ray_control_unit" },
  { code: "934", name: "X-ray Light", item_type: "x_ray_light" },
  { code: "664", name: "X-ray Viewer", item_type: "x_ray_viewer" },
  { code: "521", name: "Young Explorer", item_type: "young_explorer" },
  { code: "1405", name: "Dry Block Heater", item_type: "dry_block_heater" },
  { code: "1406", name: "Mettler Toledo", item_type: "mettler_toledo" },
  { code: "1407", name: "Function Generator", item_type: "function_generator" },
  { code: "1408", name: "Recirculating Chiller", item_type: "recirculating_chiller" },
  { code: "1409", name: "Scaler", item_type: "scaler" },
  { code: "1410", name: "Smart Cycler", item_type: "smart_cycler" },
  { code: "1411", name: "H Cube", item_type: "h_cube" },
  { code: "1455", name: "Polivac Swing Buffer", item_type: "polivac_swing_buffer" },
  { code: "1458", name: "Taski Swing Buffer", item_type: "taski_swing_buffer" },
  { code: "1459", name: "Straight Line Buffer", item_type: "straight_line_buffer" },
  { code: "1460", name: "Karcher Steam Clean", item_type: "karcher_steam_clean" },
  { code: "1461", name: "Procarpet 45", item_type: "procarpet_45" },
  { code: "1462", name: "Adiatek W/B Scrubber", item_type: "adiatek_w_b_scrubber" },
  { code: "1456", name: "Taski W/B Scrubber", item_type: "taski_w_b_scrubber" },
  { code: "1463", name: "Tennant W/B Scrubber", item_type: "tennant_w_b_scrubber" },
  { code: "1464", name: "Wet/Dry Vacuum", item_type: "wet_dry_vacuum" },
  { code: "1453", name: "Fire Extinguisher", item_type: "fire_extinguisher" },
  { code: "1454", name: "Fire Blanket", item_type: "fire_blanket" },
  { code: "1405", name: "Dry Block Heater", item_type: "dry_block_heater" },
  { code: "1406", name: "Mettler Toledo", item_type: "mettler_toledo" },
  { code: "1407", name: "Function Generator", item_type: "function_generator" },
  { code: "1408", name: "Recirculating Chiller", item_type: "recirculating_chiller" },
  { code: "1409", name: "Scaler", item_type: "scaler" },
  { code: "1410", name: "Smart Cycler", item_type: "smart_cycler" },
  { code: "1411", name: "H Cube", item_type: "h_cube" },
  { code: "1412", name: "Thermal Cycler", item_type: "thermal_cycler" },
  { code: "1413", name: "Data logger", item_type: "data_logger" },
  { code: "1414", name: "Oedometer", item_type: "oedometer" },
  { code: "1415", name: "3Ph Control Panel", item_type: "3ph_control_panel" },
  { code: "1416", name: "3Ph High Pressure Unit", item_type: "3ph_high_pressure_unit" },
  { code: "1417", name: "Compactor", item_type: "compactor" },
  { code: "1418", name: "Bale Press", item_type: "bale_press" },
  { code: "1419", name: "Gravagraph", item_type: "gravagraph" },
  { code: "1420", name: "Water Quality Meter", item_type: "water_quality_meter" },
  { code: "1421", name: "Hardness Tester", item_type: "hardness_tester" },
  { code: "1422", name: "Mixer Emulsifier", item_type: "mixer_emulsifier" },
  { code: "1423", name: "Tube Filler", item_type: "tube_filler" },
  { code: "1424", name: "Filling Line", item_type: "filling_line" },
  { code: "1425", name: "Sachet Filler", item_type: "sachet_filler" },
  { code: "1426", name: "Granulator", item_type: "granulator" },
  { code: "1427", name: "Varian Machine", item_type: "varian_machine" },
  { code: "1428", name: "Anesthesia Machine", item_type: "anesthesia_machine" },
  { code: "1429", name: "Mini Lab", item_type: "mini_lab" },
  { code: "1430", name: "Nanosight", item_type: "nanosight" },
  { code: "1431", name: "Vacuum Forming Machine", item_type: "vacuum_forming_machine" },
  { code: "1432", name: "Column Heater", item_type: "column_heater" },
  { code: "1433", name: "Dynavac", item_type: "dynavac" },
  { code: "1434", name: "Fraction Collector", item_type: "fraction_collector" },
  { code: "1435", name: "Lab Oven", item_type: "lab_oven" },
  { code: "1436", name: "Microwave Extractor", item_type: "microwave_extractor" },
  { code: "1437", name: "Polarimeter", item_type: "polarimeter" },
  { code: "1438", name: "Vacuum Cooker", item_type: "vacuum_cooker" },
  { code: "1439", name: "Vacuum Dry Oven", item_type: "vacuum_dry_oven" },
  { code: "1440", name: "Cup Warmer", item_type: "cup_warmer" },
  { code: "1441", name: "Defbrillator", item_type: "defbrillator" },
  { code: "1442", name: "Injectomat", item_type: "injectomat" },
  { code: "1443", name: "Kangaroo Pump", item_type: "kangaroo_pump" },
  { code: "1444", name: "Laerdal Suction Unit", item_type: "laerdal_suction_unit" },
  { code: "1445", name: "Isumulate", item_type: "isumulate" },
  { code: "1446", name: "Dremel", item_type: "dremel" },
  { code: "1447", name: "AC Recovery", item_type: "ac_recovery" },
  { code: "1448", name: "Sales Display", item_type: "sales_display" },
  { code: "1449", name: "Stone Heater", item_type: "stone_heater" },
  { code: "1450", name: "Spectrophotometer", item_type: "spectrophotometer" },
  { code: "1451", name: "Ultrasound", item_type: "ultrasound" },
  { code: "1452", name: "CPAP Machine", item_type: "cpap_machine" },
  { code: "914", name: "Conductor Exposed", item_type: "conductor_exposed" },
  { code: "915", name: "Single Ins. Exposed", item_type: "single_ins_exposed" },
  { code: "916", name: "Earth Continuity Fail", item_type: "earth_continuity_fail" },
  { code: "917", name: "Earth Resistance Fail", item_type: "earth_resistance_fail" },
  { code: "918", name: "Failed Polarity", item_type: "failed_polarity" },
  { code: "919", name: "Insulation Fail Test", item_type: "insulation_fail_test" },
  { code: "920", name: "Internal Fail/Short", item_type: "internal_fail_short" },
  { code: "921", name: "Damaged Power Switch", item_type: "damaged_power_switch" },
  { code: "922", name: "Damaged/Altered Plug", item_type: "damaged_altered_plug" },
  { code: "923", name: "Damaged Appliance", item_type: "damaged_appliance" },
  { code: "924", name: "No Overload Protection", item_type: "no_overload_protection" },
  { code: "925", name: "Microwave Door Fault", item_type: "microwave_door_fault" },
  { code: "926", name: "Port. RCD Time Fail", item_type: "port_rcd_time_fail" },
  { code: "927", name: "Port. RCD P/B Fail", item_type: "port_rcd_p_b_fail" },
  { code: "398", name: "Other (Please Specify)", item_type: "other_please_specify" }
];

export default items;